### ISSUE TITLE
Syntax Highlighting Breaks with Frontmatter

### ISSUE THREAD

**Issue by Lakuna** [mdx-js/mdx-analyzer#462] opened 2024-08-03 00:57 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

MDX v1.8.9

### Steps to reproduce

As of today (potentially related to the new Visual Studio Code update 1.92, which came out yesterday), MDX files with frontmatter don't display proper syntax highlighting.

1. Create a file and use MDX syntax highlighting.
2. Add frontmatter to the file.
3. Write standard MDX content below the frontmatter.

I am using Node.js version 22.3.0.

### Expected behavior

The standard syntax highlighting should appear (this was the case for me until today).

![image](https://github.com/user-attachments/assets/1f730ef4-c8b3-462d-bb47-922cc231610c)

### Actual behavior

The entire file is highlighted as if it were YAML.

![image](https://github.com/user-attachments/assets/45e075f8-fa1c-4381-98ad-67d8aac38caa)

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm v10

### OS

Windows

### Build and bundle tools

Next.js

**Comment by remcohaszing** [comment] 2024-08-03 06:53
Duplicate of https://github.com/wooorm/markdown-tm-language/issues/10

**Closed by remcohaszing** 2024-08-03 06:53 UTC
Labels: 🤞 phase/open

**Comment by remcohaszing** [comment] 2024-08-03 06:55
But it is interesting to know this was introduces by VSCode 1.92.
