### ISSUE TITLE
Incorrect highlight with markdown comment.

### ISSUE THREAD

**Issue by Debonex** [mdx-js/mdx-analyzer#319] opened 2023-04-17 02:53 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v1.3.0

### Steps to reproduce

I'm writing my blog in mdx with docusaurus, I split the blog with a markdown comment, but the syntax highlight seems incorrect in vscode.

### Expected behavior

I'm not sure how the correct syntax should behave, but the line after the angle bracket should not be highlighted.

### Actual behavior

text "the second line" is highlighted.

![image](https://user-images.githubusercontent.com/37174444/232364959-fb133aa7-7fed-4637-985e-2584d06798b2.png)

### OS

Windows

**Comment by wooorm** [comment] 2023-04-17 09:55
Hey!

Highlighting is maintained somewhere else: https://github.com/wooorm/markdown-tm-language.
So closing as it’s not something to be solved here. Feel free to comment some more if you want.

You can preview the highlighting performed: https://wooorm.com/markdown-tm-language/.
Pasting your markdown:

```
the first line

<!-- truncate -->

the second line>

the third line
```

After toggling MDX on, yields the same result.

That is the case because this is not valid MDX. See the [What is MDX](https://mdxjs.com/docs/what-is-mdx/#mdx-syntax) article on the MDX website.

This used to be okay in MDX 1 though. But as HTML comments don’t work in JSX, they are no longer supported. Docusaurus is still on MDX 1. Here’s the issue you can track for it to support MDX 2: https://github.com/facebook/docusaurus/pull/8288.

**Closed by wooorm** 2023-04-17 09:55 UTC

**Comment by thatrobotdev** [comment] 2023-09-22 02:57
Is it possible to specify language support for MDX 1 with this extension until MDX 2 is fully supported in the next version of Docusaurus?

**Comment by wooorm** [comment] 2023-09-22 09:43
MDX 2 is fully supported in the next version of Docusaurus. AFAIK it’s been years of alpha and now already in beta, I’d say it’s a very very good time to switch.

As for MDX 1, the problem is that MDX 1 is very irregular, not good to parse or highlight. Using the plain markdown highlighter might help you a bit.
