### ISSUE TITLE
Broken syntax highlighting

### ISSUE THREAD

**Issue by Reeceeboii** [mdx-js/mdx-analyzer#463] opened 2024-08-04 13:36 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

MDX v1.8.9

### Steps to reproduce

Open VSCode (`v1.92.0`), with MDX extension (`v1.8.9`), and the syntax highlighting on MDX files is broken.

This was working yesterday and appears to have suddenly become broken when I updated VSCode to the latest version.

Syntax highlighting works fine up until the closing 3 dashes `---` at the end of the frontmatter, and from then on out it's broken:

![image](https://github.com/user-attachments/assets/04cb9aa4-fb72-46ef-a44b-446eff8ae15d)
Note how the top `---` is correctly orange, but the bottom `---` is not.

All text after this appears red when it was previously white:

![image](https://github.com/user-attachments/assets/50c05f54-96b6-4a4c-9c4d-8c4ad2575bae)

I have done the typical extension uninstall/reinstall, also restarted my machine and VSCode since encountering this issue, so it's not that.

### Expected behavior

The syntax highlighting works.

### Actual behavior

The syntax highlighting doesn't work.

### Runtime

Node v20

### Package manager

npm v10

### OS

Windows

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by ChristianMurphy** [comment] 2024-08-04 14:31
Duplicate of https://github.com/wooorm/markdown-tm-language/issues/10

**Closed by ChristianMurphy** 2024-08-04 14:31 UTC
Labels: 🤞 phase/open

**Comment by Reeceeboii** [comment] 2024-08-04 15:32
https://github.com/wooorm/markdown-tm-language/issues/10#issuecomment-2265019049 solved this issue for me.
