### ISSUE TITLE
Highlighting regression in VSCode 1.92.0

### ISSUE THREAD

**Issue by ssalbdivad** [mdx-js/mdx-analyzer#464] opened 2024-08-04 18:17 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v1.8.9

### Steps to reproduce

As of VSCode 1.92.0, I see the following when viewing an Astro `.mdx` file that previously was correctly highlighted:

![Screenshot 2024-08-04 140820](https://github.com/user-attachments/assets/3a752e90-fd77-4667-87a1-cdc791e5efee)

Here is the content of that file for reference:

```mdx
---
title: ArkType
description: TypeScript's 1:1 validator, optimized from editor to runtime
template: splash
hero:
  title: ArkType
  tagline: TypeScript's 1:1 validator, optimized from editor to runtime
  image:
    alt: A serene ark, sailing to runtime
    file: ../../assets/splash.png
  actions:
    - text: Set sail
      link: /intro/setup/
      icon: right-arrow
      variant: primary
---

import {
	Card,
	CardGrid,
	LinkCard,
	TabItem,
	Tabs
} from "@astrojs/starlight/components"
import {
	RuntimeBenchmarksGraph,
	TypeBenchmarksGraph
} from "../../components/BenchmarksGraph.tsx"
import Code from "../../components/Code.astro"
import { HeroBackdrop } from "../../components/HeroBackdrop.tsx"
import betterErrors from "./betterErrors.twoslash.js?raw"
import clarityAndConcision from "./clarityAndConcision.twoslash.js?raw"
import deepIntrospectability from "./deepIntrospectability.twoslash.js?raw"
import intrinsicOptimization from "./intrinsicOptimization.twoslash.js?raw"
import unparalleledDx from "./unparalleledDx.twoslash.js?raw"

<div class="not-content">
	<HeroBackdrop client:only="react" />
</div>

## What awaits

<CardGrid stagger>
	<Card title="Unparalleled DX" icon="seti:tsconfig">
		Type syntax you already know with safety and completions unlike anything
		you've ever seen
		<Code code={unparalleledDx} />
	</Card>
	<Card title="Faster... everything" icon="rocket">
		100x faster than Zod at runtime with editor performance that will remind you
		how autocomplete is supposed to feel
		<Tabs>
			<TabItem label="Runtime">
				<RuntimeBenchmarksGraph />
			</TabItem>
			<TabItem label="Editor">
				<TypeBenchmarksGraph />
			</TabItem>
		</Tabs>
	</Card>
	<Card title="Clarity and Concision" icon="comment-alt">
		Definitions are half as long, type errors are twice as readable, and hovers
		tell you just what really matters
		<Code code={clarityAndConcision} />
	</Card>
	<Card title="Better Errors" icon="error">
		Deeply customizable messages with great defaults
		<Code code={betterErrors} />
	</Card>
	<Card title="Deep Introspectability" icon="seti:code-search">
		ArkType uses set theory to understand and expose the relationships between
		your types at runtime the way TypeScript does at compile time
		<Code code={deepIntrospectability} />
	</Card>
	<Card title="Intrinsic Optimization" icon="seti:smarty">
		Every schema is internally normalized and reduced to its purest and fastest
		representation
		<Code code={intrinsicOptimization} />
	</Card>
	{/* <Card title="Portable" icon="seti:json">
		Most definitions are just objects and strings- take them across the stack or
		even outside JS altogether
	</Card> */}
</CardGrid>

<LinkCard
	title="Doc up"
	description="Everything you need to know from installation to integration"
	href="/intro/setup"
/>
```

According to a member of the VSCode team, there are some other extensions that need to update their highlighting rules after `1.92.0`, so I thought perhaps the issue was resolvable from here.

### Expected behavior

Correct highlighting

### Actual behavior

Broken highlighting

**Comment by remcohaszing** [comment] 2024-08-04 18:30
Duplicate of https://github.com/wooorm/markdown-tm-language/issues/10

**Closed by remcohaszing** 2024-08-04 18:30 UTC
Labels: 🤞 phase/open

**Comment by ssalbdivad** [comment] 2024-08-04 18:33
@remcohaszing Whoops sorry, should have checked closed issues 🤦
