### ISSUE TITLE
Cannot find name 'frontmatter' from inside the mdx file

### ISSUE THREAD

**Issue by TeamAcarup** [mdx-js/mdx-analyzer#445] opened 2024-05-31 10:01 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

VSCode 1.89.1 / Mdx Analyser v1.8.7

### Steps to reproduce

Plugins used: "remark-frontmatter", "remark-gfm"

1. Create a mdx file with frontmatter like shown below
```mdx
---
title: "Title example"
description: "Example"
---

# {frontmatter.title}
```

### Expected behavior

The `frontmatter` object should be recognised.

### Actual behavior

The following error appears:

```
Cannot find name 'frontmatter'. ts-plugin(2304)
```

### Runtime

Node v20

### Package manager

npm v9

### OS

Windows

### Build and bundle tools

Remix

**Comment by remcohaszing** [comment] 2024-05-31 10:24
Duplicate of #297

**Closed** 2024-05-31 10:25 UTC
Labels: 🤞 phase/open

**Comment by remcohaszing** [comment] 2024-05-31 10:26
`remark-mdx-frontmatter` adds this variable.
