### ISSUE TITLE
Import statement is not highlighted

### ISSUE THREAD

**Issue by lobosan** [mdx-js/mdx-analyzer#471] opened 2024-08-20 20:40 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

Create an mdx file in an astro project and use an import statement

### Expected behavior

The import statement should be highlighted

### Actual behavior

The import looks as regular markdown
<img width="610" alt="image" src="https://github.com/user-attachments/assets/81f2f2b9-8501-4ffb-abd5-bbd3ff220a27">

### Runtime

Node v20

### Package manager

npm v10

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by ChristianMurphy** [comment] 2024-08-20 20:55
Welcome @lobosan! 👋 
Are you running the latest version of the plugin? (1.8.10 at the time of writing)
This looks a lot like a duplicate of https://github.com/mdx-js/mdx-analyzer/issues/462

**Comment by lobosan** [comment] 2024-08-20 21:05
Hi @ChristianMurphy, yes I'm running v1.8.10
<img width="830" alt="image" src="https://github.com/user-attachments/assets/4399d7ee-41aa-4717-9b73-cef60d76fa65">

**Comment by ChristianMurphy** [comment] 2024-08-20 21:17
Thanks for double checking, could you share the output from

```
code --list-extensions --show-versions
```

as well as share the text you are editing (or a minimal anonymized version of it) in a codeblock?

**Comment by lobosan** [comment] 2024-08-21 00:50
@ChristianMurphy 

`astro-build.astro-vscode@2.14.1
blackboxapp.blackbox@1.3.77
bradlc.vscode-tailwindcss@0.12.6
cardinal90.multi-cursor-case-preserve@1.0.5
chakrounanas.turbo-console-log@2.10.4
codeium.codeium@1.12.6
codium.codium@0.9.13
dbaeumer.vscode-eslint@3.0.10
dotjoshjohnson.xml@2.5.1
dracula-theme.theme-dracula@2.25.1
dsznajder.es7-react-js-snippets@4.4.3
eamodio.gitlens@15.3.0
ecmel.vscode-html-css@2.0.10
esbenp.prettier-vscode@11.0.0
github.copilot@1.223.0
github.copilot-chat@0.18.2
github.github-vscode-theme@6.3.4
graphql.vscode-graphql@0.12.0
graphql.vscode-graphql-syntax@1.3.6
mattpocock.ts-error-translator@0.10.1
meganrogge.template-string-converter@0.6.1
meshintelligenttechnologiesinc.pieces-vscode@1.17.0
moalamri.inline-fold@0.2.6
ms-vscode.live-server@0.4.14
octref.vetur@0.37.3
orta.vscode-jest@6.2.5
pkief.material-icon-theme@5.9.0
prisma.prisma@5.18.0
richie5um2.vscode-sort-json@1.20.0
ritwickdey.liveserver@5.7.9
sirtori.indenticator@0.7.0
sourcegraph.cody-ai@1.30.3
unifiedjs.vscode-mdx@1.8.10
usernamehw.errorlens@3.20.0
wallabyjs.console-ninja@1.0.350
wallabyjs.quokka-vscode@1.0.649
wix.vscode-import-cost@3.3.0
yoavbls.pretty-ts-errors@0.6.0`

**Comment by lobosan** [comment] 2024-08-21 00:52
/src/content/posts/post-1.mdx
`
---
author: { id: 87820884, name: "Lindsay Singleton", avatar: "/src/images/LindsaySingleton.jpg" }
topics: [{ id: 84596441, name: "Travel" }]
---

import VfTopics from "@/components/VfTopics.astro";

Simply post a message in the Conversations area below and Lindsday will reply to you asap. Please try to keep the questions specific to all things travel.

<VfTopics author={frontmatter.author} topics={frontmatter.topics} />

<div id="vf-conversations-container">
  <vf-conversations></vf-conversations>
</div>
`

**Comment by remcohaszing** [comment] 2024-08-21 06:05
Which version of VSCode are you using?

**Comment by wooorm** [comment] 2024-08-21 11:35
This doesn’t happen normally btw, you can try it out here: https://wooorm.com/markdown-tm-language/. That’s why we’re wondering what’s up with your stack!

**Comment by lobosan** [comment] 2024-08-21 13:53
@ChristianMurphy thanks for investigating, my issue was with the file association setting in vscode, but this fixed the issue
```
"files.associations": {
    "*.mdx": "mdx"
  }
```

**Closed** 2024-08-21 13:53 UTC
Labels: 🤞 phase/open
