### ISSUE TITLE
Syntax error in code block breaks document syntax highlighting

### ISSUE THREAD

**Issue by bradlc** [mdx-js/mdx-analyzer#468] opened 2024-08-19 12:58 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unifiedjs.vscode-mdx v1.8.9

### Steps to reproduce

1. Create a new MDX file in VS Code
2. Copy the following code in to the document (note the missing closing bracket):
   ````mdx
   ```ts
   console.log('hi'
   ```

   <Example prop="test" />
   ````

### Expected behavior

The MDX code following the code block `<Example prop="test" />` should be syntax highlighted correctly, as it is when the code block is valid:

![CleanShot 2024-08-19 at 13 53 27@2x](https://github.com/user-attachments/assets/20e48517-e3c3-41f7-903d-a9091da82bcd)

### Actual behavior

The MDX code following the code block is not syntax highlighted correctly.

![CleanShot 2024-08-19 at 13 53 12@2x](https://github.com/user-attachments/assets/5e837168-652c-43d4-a8af-974f8f30e48a)

### Runtime

VS Code 1.92.1

### OS

macOS

**Comment by wooorm** [comment] 2024-08-19 13:00
Heya! 

Why you put syntax errors in code? 🤷‍♂️

Like, if I write broken typescript in VS code, it also highlights “weirdly”?

**Comment by bradlc** [comment] 2024-08-19 13:19
Hey @wooorm. I can think of several reasons why you might do this. You might be documenting what _not_ to do, or your code snippet may be a partial snippet that is not syntactically valid on its own, for example:

> Change the function name to be `foo`:
>
> ```js
> function foo() {
> ```

Although I personally think that code snippets should be syntactically valid where possible, I think this is _absolutely_ a valid thing to do and something that should not affect document syntax highlighting.

> _Like, if I write broken typescript in VS code, it also highlights “weirdly”?_

Code inside a MDX/Markdown code block is typically not executed so syntactic validity is not important in the same way. Also, the syntax highlighting **inside the code block** looking weird is expected, but **code block syntax highlighting should be isolated from the MDX document highlighting**, in my opinion.

For what it's worth the **Markdown** language is VS Code doesn't have this issue.

**Comment by wooorm** [comment] 2024-08-19 13:24
But why call it TS if it is broken? I have started using ` ```mdx-broken ` when I show broken MDX, and the like.

With `rehype-twoslash`, which you can see in use on the MDX website, the javascript/typescript *is* evaluated.

**Comment by wooorm** [comment] 2024-08-19 13:25
Anyway, it’s a duplicate of https://github.com/wooorm/markdown-tm-language/issues/9, it’s already done

**Comment by remcohaszing** [comment] 2024-08-19 13:27
This looks similar to, but not the same as, https://github.com/microsoft/vscode/issues/224862. I agree ideally broken code blocks shouldn’t break syntax highlighting.

The linked issue was acknowledged to be a bug upstream and fixed, but there was a hint on how the MDX grammar could be improved to handle that situation in https://github.com/microsoft/vscode/issues/224862#issuecomment-2269917129.

Syntax highlighting of code blocks after can be broken due to unforeseen bugs in arbritrary grammars. I think this example is a bit silly, but it makes sense. Also I imagine it can be annoying if MDX highlighting outside the codeblock changes every time you open or close a quote inside a TypeScript code block.

**Comment by wooorm** [comment] 2024-08-19 13:39
@remcohaszing ping to make sure you saw my last comment.

**Comment by bradlc** [comment] 2024-08-19 13:40
> _Anyway, it’s a duplicate of https://github.com/wooorm/markdown-tm-language/issues/9, it’s already done_

This does look like the same issue, thanks! Sorry I didn't find that earlier. Do you have an idea of when the fix will land in the MDX extension?

> _I agree ideally broken code blocks shouldn’t break syntax highlighting._

💯

**Comment by remcohaszing** [comment] 2024-08-19 14:00
It’s similar, but not a duplicate. https://github.com/wooorm/markdown-tm-language/issues/9 / https://github.com/microsoft/vscode/issues/224862 was explicitly about the YAML grammar being broken upstream. That’s fixed.

Based on https://github.com/microsoft/vscode/issues/224862#issuecomment-2269917129 I think we can be more defensive against broken grammars in code blocks (and frontmatter). I’m not going to pretend to fully understand these grammars though. I could easily be wrong.

**Comment by wooorm** [comment] 2024-08-19 14:05
No, the issue is not about yaml. It's about code.

The solution is for the grammar to be pulled into this project

**Comment by remcohaszing** [comment] 2024-08-19 14:37
Oh wow, I totally misread that and was mixing up things. You’re right, this is fixed upstream already

**Closed** 2024-08-19 14:56 UTC
Labels: 🐛 type/bug, 📦 area/deps, 👶 semver/patch, 🙆 yes/confirmed, 👍 phase/yes
