### ISSUE TITLE
Prettier formatting breaks JSDoc comments

### ISSUE THREAD

**Issue by karlhorky** [mdx-js/mdx-analyzer#454] opened 2024-07-07 20:25 UTC
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

prettier@3.3.2, @mdx-js/react@3.0.1, next@14.2.4, react@^18

### Steps to reproduce

1. Ensure [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) is installed
2. Copy the example from [the Props section in the readme](https://github.com/mdx-js/mdx-analyzer#props) to an MDX file
3. Format the file with Prettier
4. Observe backslashes added before asterisk characters and the error message below
   ```
   Could not parse expression with acorn MDX micromark-extension-mdx-expression:acorn
   ```
5. Replace the multi-line JSDoc comment with a single-line JSDoc block
6. Format the file with Prettier
7. Observe space being added before second asterisk character and error message below
   ```
   Property 'name' does not exist on type '{ readonly components?: {} | undefined; }'. ts-plugin(2339)
   ```

Prettier Input/Output:

**Input:**

```mdx
{/**
  * @typedef Props
  * @property {string} name
  *   Who to greet.
  */}

{/** @typedef Props @property {string} name2 Who to greet. */}

# Hello {props.name} and {props.name2}
```

**Output:**

```mdx
{/\*\*

- @typedef Props
- @property {string} name
- Who to greet.
  \*/}

{/* * @typedef Props @property {string} name2 Who to greet. */}

# Hello {props.name} and {props.name2}

```

https://github.com/mdx-js/mdx-analyzer/assets/1935696/8967a357-a093-4137-93ae-0144874834e9

### Companion issue in `prettier/prettier`

I've also reported this as an issue in `prettier/prettier`:

- https://github.com/prettier/prettier/issues/16457

If it's desired to only track it in `prettier/prettier`, then this issue can be closed.

### Expected behavior

No problems with Prettier formatting using MDX comments with JSDoc

### Actual behavior

Problems with Prettier formatting using MDX comments with JSDoc

### Runtime

Node v20

### OS

macOS

**Comment by ChristianMurphy** [comment] 2024-07-08 02:18
Thanks for sharing @karlhorky!
Prettier has a number of issues with MDX 3 comments.
I'm not sure the language server can smooth those over, it probably needs to be reolved upstream, but @remcohaszing may know best.

**Comment by remcohaszing** [comment] 2024-07-08 07:25
Duplicate of #415

**Closed by remcohaszing** 2024-07-08 07:25 UTC
Labels: 🤞 phase/open

**Comment by karlhorky** [comment] 2024-07-08 08:41
## Workaround

Ignore any JSDoc comments until [MDX v2+ comments w. JSDoc support](https://github.com/prettier/prettier/issues/16457) or [MDX v3 support](https://github.com/prettier/prettier/issues/12209) added:

```mdx
{/* prettier-ignore-start */}

{/**
  * @typedef Props
  * @property {string} name
  *   Who to greet.
  */}

{/* prettier-ignore-end */}

# Hello {props.name}
```

Also added an MDX Analyzer PR here:

- https://github.com/mdx-js/mdx-analyzer/pull/455
